server:
  port: 8888
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jabborovjaloliddin9/investment-configurations.git
          username: jabborovjaloliddin9
          password: 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
          default-label: master
          clone-on-start: true
