spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
  config:
    import: optional:configserver:http://localhost:8888/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
