spring:
  application:
    name: service-registration
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
  config:
    import: optional:configserver:http://localhost:8888/
